// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCazS_EayGaR0PDI89RFHP5XgADR2F6SPk',
    appId: '1:808354604817:web:51089a1b76da8d3a164eb0',
    messagingSenderId: '808354604817',
    projectId: 'skyroster-1103f',
    authDomain: 'skyroster-1103f.firebaseapp.com',
    storageBucket: 'skyroster-1103f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0QoVMUdq2NAHGvpmHHHbUO_hRxye-Crs',
    appId: '1:808354604817:android:3a905f6561430a0b164eb0',
    messagingSenderId: '808354604817',
    projectId: 'skyroster-1103f',
    storageBucket: 'skyroster-1103f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu38uIXFD0QyCsivTT4-wttvBwvyF7Q6c',
    appId: '1:808354604817:ios:7fb1a5460281f008164eb0',
    messagingSenderId: '808354604817',
    projectId: 'skyroster-1103f',
    storageBucket: 'skyroster-1103f.firebasestorage.app',
    iosBundleId: 'com.example.airLineApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu38uIXFD0QyCsivTT4-wttvBwvyF7Q6c',
    appId: '1:808354604817:ios:7fb1a5460281f008164eb0',
    messagingSenderId: '808354604817',
    projectId: 'skyroster-1103f',
    storageBucket: 'skyroster-1103f.firebasestorage.app',
    iosBundleId: 'com.example.airLineApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCazS_EayGaR0PDI89RFHP5XgADR2F6SPk',
    appId: '1:808354604817:web:44fddc481b410a31164eb0',
    messagingSenderId: '808354604817',
    projectId: 'skyroster-1103f',
    authDomain: 'skyroster-1103f.firebaseapp.com',
    storageBucket: 'skyroster-1103f.firebasestorage.app',
  );
}
